export const LOAD_START = 'IMAGES/LOAD_START';
export const LOAD_SUCCESS = 'IMAGES/LOAD_SUCCESS';
export const SEARCH = 'IMAGES/SEARCH';
export const TOGGLE_PHOTO_LIKE = 'IMAGES/TOGGLE_PHOTO_LIKE';
export const TOGGLE_PHOTO_UNLIKE = 'IMAGES/TOGGLE_PHOTO_UNLIKE';
export const SET_SEARCH_OPTIONS = 'SET_SEARCH_OPTIONS';
