export const IMAGE_LOADING_START = 'IMAGES/IMAGE_LOADING_START';
export const IMAGE_LOADING_SUCCESS = 'IMAGES/IMAGE_LOADING_SUCCESS';
export const IMAGE_LOADING_ERROR = 'IMAGES/IMAGE_LOADING_ERROR';
export const SET_SEARCH_INPUT = 'IMAGES/SET_SEARCH_INPUT';
export const TOGGLE_PHOTO_LIKE = 'IMAGES/TOGGLE_PHOTO_LIKE';
export const TOGGLE_PHOTO_UNLIKE = 'IMAGES/TOGGLE_PHOTO_UNLIKE';
export const SET_SEARCH_OPTIONS = 'SET_SEARCH_OPTIONS';
